image: node:16.19.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@10.1.3
    - npm install --force
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages